openapi: "3.0.0"
info:
  version: 1.0.0
  title: Benefit Checker API
paths:
  /api/v1/benefitsCheck:
    post:
      tags:
        - benefitsChecker
      summary: Perform a benefits check
      operationId: benefitCheck
      requestBody:
        description: perform a benefits check
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BenefitCheckRequestBody'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BenefitCheckResponseBody'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
components:
  schemas:
    BenefitCheckRequestBody:
      required:
        - clientReference
        - nino
        - surname
        - dateOfBirth
        - dateOfAward
        - lscServiceName
        - clientOrgId
        - clientUserId
      properties:
        clientReference:
          type: string
        nino:
          type: string
        surname:
          type: string
        dateOfBirth:
          type: string
          example: 19720110
        dateOfAward:
          type: string
          example: 20260205
        lscServiceName:
          type: string
        clientOrgId:
          type: string
        clientUserId:
          type: string
    BenefitCheckResponseBody:
      required:
        - originalClientRef
        - benefitCheckerStatus
        - confirmationRef
      properties:
        originalClientRef:
          type: string
        benefitCheckerStatus:
          type: string
          example: Yes or No
        confirmationRef:
          type: string