# Default values for dwp-benefit-checker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: null
  tag: null

service_account:
  name: laa-dwp-benefit-checker-prod-service-account

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

ingressInternal:
  enabled: true
  className: internal
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-dwp-benefit-checker-internal-laa-dwp-benefit-checker-prod-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts: 
    - "laa-dwp-benefit-checker.internal.cloud-platform.service.justice.gov.uk"

resources:
  limits:
    cpu: 1000m
    memory: 1G
  requests:
    cpu: 25m
    memory: 1G

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

sentry:
  enabled: true
  environment: production
  tracesSampleRate: 1