# Default values for dwp-benefit-checker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-access-court-data/laa-benefit-checker-interim-uat

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: modsec
  environmentName: laa-benefit-checker-interim-prod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-benefit-checker-interim-laa-benefit-checker-interim-prod-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-access-court-data,tag:namespace=laa-benefit-checker-interim-prod"
  internalHost:
    host: "laa-benefit-checker-interim.apps.live.cloud-platform.service.justice.gov.uk"
    path: /

resources:
  limits:
    cpu: 1000m
    memory: 1G
  requests:
    cpu: 25m
    memory: 1G

spring:
  profile: production

aws:
  region: eu-west-2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

sentry:
  enabled: true
  environment: production
  tracesSampleRate: 1