spring:
  application:
    name: LAA Benefit Checker 2.0
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            entity-id: caab-provider-ui
            assertingparty:
              metadata-uri: ${PORTAL_URL}/oamfed/idp/metadata
              singlesignon:
                url: ${PORTAL_URL}/oamfed/idp/initiatesso?providerid=${spring.security.saml2.relyingparty.registration.idp.entity-id}
            signing:
              credentials:
                private-key: ${SAML_PRIVATE_KEY}
                certificate: ${SAML_CERTIFICATE}

# used by actuator info endpoint
info:
  app:
    name: LAA Benefit Checker 2.0 application
    description: A service that provides a REST API to determine if a person is on benefits or not.
    version: 1.0.0

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health
