name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      docker_image:
        type: string
        description: Image tag to deploy (suffix only)

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy
        id: deploy_to_prod
        uses: ./.github/actions/deploy_image
        with:
          ecr-region: ${{ vars.ECR_REGION }}
          ecr-role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          docker-image: ${{ github.event.inputs.docker_image }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          app-environment: production
